### ISSUE TITLE
How install 'qsub'?

### ISSUE THREAD

**Issue by aiqubo** [pommevilla/MetaFunPrimer#28]
Checking diamond: OK.
Checking python: OK.
Checking blastx: OK.
Checking cd-hit: OK.
Checking clustalo-1.2.4-Ubuntu-x86_64: OK.
Checking parallel: OK.
Checking qsub: Failed.

can you help me with this? How do I install 'qsub'?

**Comment by PabloArrow** [comment]
were you able to install it? the website doesn't give any details.
