### ISSUE TITLE
Primer design file prepared

### ISSUE THREAD

**Issue by aiqubo** [pommevilla/MetaFunPrimer#30]
How do I prepare these file which Like in the example , such as  "/sample_metagenomes" and "rpoB_sample_data".
thank you very much

**Comment by pommevilla** [comment]
Hi, sorry about responding so late. I wasn't receiving email notifications about this. I just pushed an updated version of this pipeline and you should now be able to find these files in `MetaFunPrimer/tests/test_data/rpoB_sample_data/`. Let me know how it goes or if you need any help!

**Comment by aiqubo** [comment]
Thank you for your feedback .
It's very useful to me

qubo
